import { useOutletContext } from "react-router-dom";

function ProductSpecificationsPanel() {
  const { name } = useOutletContext();

  const specificationSets = {
    "Canon EF 24-70mm f/2.8L II USM": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "EF 24-70mm f/2.8L II USM" },
      { label: "焦段", value: "24–70mm" },
      { label: "最大光圈", value: "f/2.8（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "18 組 20 枚鏡片" },
      { label: "光圈葉片", value: "9 片圓形光圈" },
      { label: "最近對焦距離", value: "約 38cm" },
      { label: "放大倍率", value: "約 0.24 倍" },
      { label: "對焦驅動", value: "超音波馬達（USM）" },
      { label: "濾鏡尺寸", value: "82mm" },
      { label: "尺寸", value: "約 88.5 × 113 mm" },
      { label: "重量", value: "約 805g" },
      { label: "防塵防滴", value: "具備" },
      { label: "接環類型", value: "Canon EF" },
      { label: "產地", value: "日本" },
    ],
    "Canon EOS 5D Mark IV": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "EOS 5D Mark IV" },
      { label: "感光元件", value: "全片幅 CMOS" },
      { label: "有效畫素", value: "約 3040 萬像素" },
      { label: "影像處理器", value: "DIGIC 6+" },
      { label: "感光度範圍", value: "ISO 100–32000（可擴展至 50–102400）" },
      { label: "對焦系統", value: "61 點高密度自動對焦（41 點十字型）" },
      { label: "快門速度", value: "1/8000 至 30 秒，支援 B 快門" },
      { label: "連拍速度", value: "約 7 fps" },
      { label: "錄影功能", value: "4K 30p、Full HD 60p" },
      { label: "螢幕", value: "3.2 吋固定式 TFT LCD（約 162 萬點）" },
      { label: "觀景窗", value: "光學五稜鏡，約 100% 視野率" },
      { label: "儲存媒介", value: "雙 SD 卡槽（UHS-I 支援）" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 150.7 × 116.4 × 75.9 mm" },
      { label: "重量", value: "約 890g（含電池與卡）" },
      { label: "電池", value: "LP-E6N" },
      { label: "產地", value: "日本" },
    ],
    "Canon EOS R6": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "EOS R6" },
      { label: "感光元件", value: "全片幅 CMOS" },
      { label: "有效畫素", value: "約 2010 萬像素" },
      { label: "影像處理器", value: "DIGIC X" },
      { label: "感光度範圍", value: "ISO 100–102400（可擴展至 50–204800）" },
      { label: "對焦系統", value: "Dual Pixel CMOS AF II，1053 點自動對焦" },
      { label: "防手震系統", value: "機身五軸防震，最高約 8 級補償" },
      { label: "快門速度", value: "1/8000 至 30 秒，支援 B 快門" },
      { label: "連拍速度", value: "最高約 12 fps（機械快門）、20 fps（電子快門）" },
      { label: "錄影功能", value: "4K 60p、Full HD 120p" },
      { label: "螢幕", value: "3 吋可翻轉觸控 LCD（約 162 萬點）" },
      { label: "電子觀景窗", value: "369 萬點 OLED" },
      { label: "儲存媒介", value: "雙 SD 卡槽（UHS-II 支援）" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 138.4 × 97.5 × 88.4 mm" },
      { label: "重量", value: "約 680g（含電池與卡）" },
      { label: "電池", value: "LP-E6NH" },
      { label: "產地", value: "日本" },
    ],
    "Canon LP-E6NH 原廠電池": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "LP-E6NH" },
      { label: "電池類型", value: "鋰離子可充電電池" },
      { label: "容量", value: "2130mAh" },
      { label: "電壓", value: "7.2V" },
      { label: "續航表現", value: "約 510 張（CIPA 標準）" },
      { label: "相容機種", value: "EOS R5、R6、5D Mark IV、6D Mark II 等" },
      { label: "尺寸", value: "約 38 × 54 × 21 mm" },
      { label: "重量", value: "約 80g" },
      { label: "產地", value: "日本" },
    ],
    "Canon PowerShot G1 X Mark III": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "PowerShot G1 X Mark III" },
      { label: "感光元件", value: "APS-C CMOS" },
      { label: "有效畫素", value: "約 2410 萬像素" },
      { label: "影像處理器", value: "DIGIC 7" },
      { label: "感光度範圍", value: "ISO 100–25600" },
      { label: "對焦系統", value: "Dual Pixel CMOS AF，最大 31 點對焦" },
      { label: "快門速度", value: "1/4000 至 30 秒，支援 B 快門" },
      { label: "錄影功能", value: "Full HD 60p" },
      { label: "螢幕", value: "3 吋可翻折觸控 LCD（約 104 萬點）" },
      { label: "儲存媒介", value: "SD / SDHC / SDXC" },
      { label: "尺寸", value: "約 116.3 × 74.3 × 51.3 mm" },
      { label: "重量", value: "約 399g（含電池與卡）" },
      { label: "防塵防滴", value: "具備" },
      { label: "產地", value: "日本" },
    ],
    "Canon PowerShot G7 X Mark III": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "PowerShot G7 X Mark III" },
      { label: "感光元件", value: "1 吋 CMOS" },
      { label: "有效畫素", value: "約 2010 萬像素" },
      { label: "影像處理器", value: "DIGIC 7" },
      { label: "感光度範圍", value: "ISO 125–12800" },
      { label: "對焦系統", value: "對比式自動對焦" },
      { label: "快門速度", value: "1/2000 至 30 秒，支援 B 快門" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "螢幕", value: "3 吋可翻折觸控 LCD（約 104 萬點）" },
      { label: "儲存媒介", value: "SD / SDHC / SDXC" },
      { label: "尺寸", value: "約 103 × 60 × 41 mm" },
      { label: "重量", value: "約 304g（含電池與卡）" },
      { label: "產地", value: "日本" },
    ],
    "Canon RF 15-35mm f/2.8L IS USM": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "RF 15-35mm f/2.8L IS USM" },
      { label: "焦段", value: "15–35mm" },
      { label: "最大光圈", value: "f/2.8（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "14 組 18 枚" },
      { label: "光圈葉片", value: "9 片圓形光圈" },
      { label: "最近對焦距離", value: "約 28 cm" },
      { label: "放大倍率", value: "約 0.28 倍" },
      { label: "對焦驅動", value: "環型超音波馬達（USM）" },
      { label: "影像穩定", value: "具備光學防手震" },
      { label: "濾鏡尺寸", value: "82mm" },
      { label: "尺寸", value: "約 88.5 × 129.8 mm" },
      { label: "重量", value: "約 840g" },
      { label: "接環類型", value: "Canon RF" },
      { label: "產地", value: "日本" },
    ],
    "Canon Speedlite 600EX II-RT": [
      { label: "品牌", value: "Canon" },
      { label: "型號", value: "Speedlite 600EX II-RT" },
      { label: "閃光指數", value: "GN60（ISO 100，200mm）" },
      { label: "閃燈覆蓋範圍", value: "20–200mm（手動 / 自動變焦）" },
      { label: "閃光模式", value: "E-TTL II / 手動 / 多重閃光" },
      { label: "無線控制", value: "支援無線觸發及群組控制" },
      { label: "LED 輔助燈", value: "有" },
      { label: "對焦輔助燈", value: "有" },
      { label: "電池", value: "4 顆 AA 電池" },
      { label: "尺寸", value: "約 76 × 116 × 93 mm" },
      { label: "重量", value: "約 425g（不含電池）" },
      { label: "產地", value: "日本" },
    ],

    "Fujifilm X100V": [
      { label: "品牌", value: "Fujifilm" },
      { label: "型號", value: "X100V" },
      { label: "感光元件", value: "APS-C X-Trans CMOS 4" },
      { label: "有效畫素", value: "約 2610 萬畫素" },
      { label: "鏡頭規格", value: "23mm f/2（等效全幅 35mm）" },
      { label: "對焦系統", value: "混合式（相位 + 對比）425 點對焦" },
      { label: "觀景窗", value: "混合式（光學 OVF + 電子 EVF）" },
      { label: "螢幕", value: "3 吋可翻折觸控螢幕，162 萬點" },
      { label: "錄影功能", value: "4K/30p、F-Log、10-bit via HDMI" },
      { label: "ISO 感光度", value: "ISO 160–12800（擴展至 80–51200）" },
      { label: "快門速度", value: "機械快門 1/4000s，電子快門 1/32000s" },
      { label: "儲存媒介", value: "單張 SD（支援 UHS-I）" },
      { label: "連接功能", value: "Wi-Fi、藍牙 4.2" },
      { label: "電池", value: "NP-W126S，約 350 張（CIPA）" },
      { label: "防滴防塵", value: "具備（需搭配濾鏡）" },
      { label: "尺寸", value: "約 128 × 75 × 53 mm" },
      { label: "重量", value: "約 478g（含電池）" },
    ],
    "Fujifilm X-T3": [
      { label: "品牌", value: "Fujifilm" },
      { label: "型號", value: "X-T3" },
      { label: "感光元件", value: "APS-C X-Trans CMOS 4，2610 萬畫素" },
      { label: "影像處理器", value: "X-Processor 4" },
      { label: "對焦系統", value: "相位與對比混合式對焦，425 點" },
      { label: "觀景窗", value: "369 萬點 OLED 電子觀景窗" },
      { label: "螢幕", value: "3 吋 3 向翻轉觸控螢幕" },
      { label: "錄影功能", value: "4K/60p、F-Log、10-bit HDMI 輸出" },
      { label: "ISO 感光度", value: "ISO 160–12800（擴展至 80–51200）" },
      { label: "快門速度", value: "機械快門 1/8000s，電子快門 1/32000s" },
      { label: "連拍速度", value: "11 fps（機械）/ 20 fps（電子）" },
      { label: "記憶卡插槽", value: "雙 SD 卡槽（支援 UHS-II）" },
      { label: "無線功能", value: "Wi-Fi、藍牙" },
      { label: "電池", value: "NP-W126S，約 390 張（CIPA）" },
      { label: "防滴防塵", value: "具備" },
      { label: "尺寸", value: "約 133 × 93 × 59 mm" },
      { label: "重量", value: "約 539g（含電池）" },
    ],
    "Fujifilm XF 16-55mm f/2.8 R LM WR": [
      { label: "品牌", value: "Fujifilm" },
      { label: "型號", value: "XF 16-55mm f/2.8 R LM WR" },
      { label: "鏡頭格式", value: "APS-C" },
      { label: "焦段", value: "16–55mm（等效 24–84mm）" },
      { label: "最大光圈", value: "f/2.8（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "光圈葉片", value: "9 片圓形" },
      { label: "鏡片結構", value: "14 組 17 枚（含 3 非球面與 3 ED 鏡片）" },
      { label: "最近對焦距離", value: "約 30cm（廣角端）" },
      { label: "最大放大倍率", value: "約 0.16 倍" },
      { label: "對焦驅動", value: "雙線性馬達" },
      { label: "濾鏡尺寸", value: "77mm" },
      { label: "尺寸", value: "約 83.3 × 106 mm" },
      { label: "重量", value: "約 655g" },
      { label: "防滴防塵", value: "具備" },
    ],
    "Fujifilm XF 56mm f/1.2 R": [
      { label: "品牌", value: "Fujifilm" },
      { label: "型號", value: "XF 56mm f/1.2 R" },
      { label: "鏡頭格式", value: "APS-C" },
      { label: "焦段", value: "56mm（等效 85mm）" },
      { label: "最大光圈", value: "f/1.2" },
      { label: "最小光圈", value: "f/16" },
      { label: "光圈葉片", value: "7 片圓形" },
      { label: "鏡片結構", value: "8 組 11 枚（含 1 非球面與 2 ED 鏡片）" },
      { label: "最近對焦距離", value: "約 0.7 公尺" },
      { label: "最大放大倍率", value: "約 0.09 倍" },
      { label: "對焦方式", value: "內對焦（步進馬達）" },
      { label: "濾鏡尺寸", value: "62mm" },
      { label: "尺寸", value: "約 73.2 × 69.7 mm" },
      { label: "重量", value: "約 405g" },
      { label: "防滴防塵", value: "無" },
    ],
    "Fujifilm VG-XT3 直立手把": [
      { label: "品牌", value: "Fujifilm" },
      { label: "型號", value: "VG-XT3" },
      { label: "適用機種", value: "Fujifilm X-T3" },
      { label: "電池容量", value: "可裝載 2 顆 NP-W126S 電池" },
      { label: "續航提升", value: "增加拍攝張數至約 1100 張（CIPA 標準）" },
      { label: "防塵防滴", value: "具備，與 X-T3 相同等級密封設計" },
      { label: "尺寸", value: "約 134.5 × 49.1 × 75.3 mm" },
      { label: "重量", value: "約 279 g（不含電池）" },
      { label: "附屬配件", value: "原廠包裝、AC 電源供應器（型號 AC-9VS）" },
    ],

    "Hasselblad X1D II 50C": [
      { label: "品牌", value: "Hasselblad" },
      { label: "型號", value: "X1D II 50C" },
      { label: "感光元件", value: "5000 萬畫素中片幅 CMOS（43.8 x 32.9 mm）" },
      { label: "色彩深度與動態範圍", value: "16-bit 色彩，14 檔動態範圍" },
      { label: "快門速度", value: "1/2000 秒至 60 分鐘（電子快門）" },
      { label: "連拍速度", value: "約 2.7 fps" },
      { label: "自動對焦系統", value: "對比式自動對焦（CDAF）" },
      { label: "螢幕", value: "3.6 吋觸控 LCD（236 萬點）" },
      { label: "觀景窗", value: "369 萬點 OLED EVF" },
      { label: "儲存媒體", value: "雙 SD 卡槽（支援 UHS-II）" },
      { label: "連接介面", value: "USB-C、Wi-Fi、GPS（透過手機）" },
      { label: "機身尺寸", value: "148 × 97 × 70 mm" },
      { label: "重量", value: "約 766g（含電池）" },
      { label: "鏡頭接環", value: "Hasselblad XCD 系列" },
    ],
    "Hasselblad XCD 45mm f/3.5": [
      { label: "品牌", value: "Hasselblad" },
      { label: "型號", value: "XCD 45mm f/3.5" },
      { label: "焦距", value: "45mm（等效全幅約 35mm）" },
      { label: "光圈範圍", value: "f/3.5 – f/32" },
      { label: "鏡頭結構", value: "9 群 10 枚" },
      { label: "最近對焦距離", value: "40 cm" },
      { label: "最大放大倍率", value: "0.1x" },
      { label: "快門系統", value: "內建中央快門（Leaf Shutter），最高 1/2000 秒" },
      { label: "自動對焦", value: "支援自動與手動對焦" },
      { label: "濾鏡尺寸", value: "67mm" },
      { label: "尺寸", value: "75 × 77 mm" },
      { label: "重量", value: "約 417g" },
      { label: "適用機型", value: "Hasselblad X 系列相機（如 X1D、X1D II、X2D）" },
    ],
    "Hasselblad X1D 電池": [
      { label: "品牌", value: "Hasselblad" },
      { label: "型號", value: "3034757" },
      { label: "適用機種", value: "Hasselblad X1D、X1D II、X2D 系列" },
      { label: "電池種類", value: "可充式鋰電池（Rechargeable Li-ion）" },
      { label: "容量", value: "3200mAh / 23.3Wh" },
      { label: "電壓", value: "7.27V" },
      { label: "充電方式", value: "支援原廠充電器與機身 USB-C 充電" },
      { label: "續航表現", value: "約 300–400 張（視機型與設定）" },
      { label: "尺寸", value: "約 70 × 40 × 20 mm" },
      { label: "重量", value: "約 100g" },
      { label: "附屬配件", value: "視庫存而定，可能含電池盒" },
    ],

    "Leica D-Lux 7": [
      { label: "品牌", value: "Leica" },
      { label: "型號", value: "D-Lux 7" },
      { label: "感光元件", value: "4/3 吋 MOS" },
      { label: "有效畫素", value: "約 1700 萬畫素" },
      { label: "鏡頭規格", value: "Leica DC Vario-Summilux 10.9–34mm（等效 24–75mm）f/1.7–2.8" },
      { label: "螢幕", value: "3 吋觸控 LCD 螢幕" },
      { label: "電子觀景窗", value: "約 276 萬點" },
      { label: "錄影功能", value: "4K UHD / 30fps" },
      { label: "無線連接", value: "Wi-Fi、Bluetooth" },
      { label: "機身尺寸", value: "約 118 × 66 × 64 mm" },
      { label: "重量", value: "約 403g（含電池）" },
    ],
    "Leica M10": [
      { label: "品牌", value: "Leica" },
      { label: "型號", value: "M10" },
      { label: "感光元件", value: "全片幅 CMOS" },
      { label: "有效畫素", value: "約 2400 萬畫素" },
      { label: "影像處理器", value: "Leica Maestro II" },
      { label: "對焦方式", value: "手動對焦（旁軸連動）" },
      { label: "觀景窗", value: "光學旁軸觀景窗（放大率 0.73x）" },
      { label: "螢幕", value: "3 吋 LCD，約 103 萬點" },
      { label: "感光度", value: "ISO 100–50000" },
      { label: "快門速度", value: "8s 至 1/4000s" },
      { label: "錄影功能", value: "不支援錄影" },
      { label: "無線連接", value: "Wi-Fi（支援 Leica FOTOS）" },
      { label: "機身尺寸", value: "約 139 × 80 × 38.5 mm" },
      { label: "重量", value: "約 660g（含電池）" },
    ],
    "Leica SF 60 閃光燈": [
      { label: "品牌", value: "Leica" },
      { label: "型號", value: "SF 60" },
      { label: "閃光指數", value: "GN60（ISO 100，200mm）" },
      { label: "閃燈覆蓋範圍", value: "24–200mm（自動變焦）" },
      { label: "閃光模式", value: "TTL / 手動 / HSS（高速同步）" },
      { label: "無線控制", value: "支援（需搭配 SF C1）" },
      { label: "LED 輔助燈", value: "有" },
      { label: "對焦輔助燈", value: "有" },
      { label: "電池", value: "4 顆 AA 電池" },
      { label: "外接電源", value: "支援（如 Power Pack）" },
      { label: "螢幕", value: "背光 LCD 顯示" },
      { label: "重量", value: "約 300g（不含電池）" },
      { label: "相容機種", value: "Leica M / SL / Q 系列支援 TTL 相機" },
    ],
    "Leica Summilux-M 50mm f/1.4 ASPH": [
      { label: "品牌", value: "Leica" },
      { label: "型號", value: "Summilux-M 50mm f/1.4 ASPH" },
      { label: "焦段", value: "50mm（標準定焦）" },
      { label: "最大光圈", value: "f/1.4" },
      { label: "最小光圈", value: "f/16" },
      { label: "鏡片組成", value: "8 群 9 枚（含 1 枚非球面鏡片）" },
      { label: "最近對焦距離", value: "約 0.7 公尺" },
      { label: "對焦方式", value: "手動對焦" },
      { label: "濾鏡尺寸", value: "46mm" },
      { label: "尺寸", value: "約 53mm（長） × 59mm（直徑）" },
      { label: "重量", value: "約 335g" },
      { label: "接環類型", value: "Leica M 接環" },
      { label: "產地", value: "德國" },
    ],

    "Nikon AF-S 70-200mm f/2.8E FL ED VR": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "AF-S 70-200mm f/2.8E FL ED VR" },
      { label: "焦段", value: "70–200mm" },
      { label: "最大光圈", value: "f/2.8（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "16 組 21 枚（含 3 枚萊卡 ED 鏡片與氟素鍍膜）" },
      { label: "光圈葉片", value: "9 片圓形光圈" },
      { label: "最近對焦距離", value: "約 1.1 公尺" },
      { label: "最大放大倍率", value: "0.21 倍" },
      { label: "影像穩定", value: "VR（震動減低）" },
      { label: "濾鏡尺寸", value: "77mm" },
      { label: "尺寸", value: "約 88 × 200 mm" },
      { label: "重量", value: "約 1430 g" },
      { label: "接環類型", value: "Nikon F（全片幅）" },
      { label: "防塵防滴", value: "有" },
      { label: "產地", value: "泰國" },
    ],

    "Nikon COOLPIX P1000": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "COOLPIX P1000" },
      { label: "感光元件", value: "1/2.3 吋 CMOS" },
      { label: "有效畫素", value: "約 1600 萬像素" },
      { label: "鏡頭焦段", value: "24–3000mm（等效全片幅）" },
      { label: "最大光圈", value: "f/2.8–8" },
      { label: "光學變焦", value: "125 倍" },
      { label: "影像穩定", value: "VR（光學防震）" },
      { label: "螢幕", value: "3.2 吋翻轉 LCD（約 92 萬點）" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "儲存媒介", value: "SD / SDHC / SDXC" },
      { label: "尺寸", value: "約 146.3 × 118.8 × 181.3 mm" },
      { label: "重量", value: "約 1415 g（含電池與卡）" },
      { label: "電池", value: "EN-EL20a" },
      { label: "產地", value: "中國" },
    ],

    "Nikon D850": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "D850" },
      { label: "感光元件", value: "35.9 × 23.9 mm CMOS" },
      { label: "有效畫素", value: "約 4575 萬像素" },
      { label: "影像處理器", value: "EXPEED 5" },
      { label: "感光度範圍", value: "ISO 64–25600（可擴展至 32–102400）" },
      { label: "對焦系統", value: "153 點自動對焦（99 點十字型）" },
      { label: "快門速度", value: "1/8000 至 30 秒，支援 B 快門" },
      { label: "連拍速度", value: "最高約 7 fps（加電池手把可至 9 fps）" },
      { label: "螢幕", value: "3.2 吋可翻轉觸控 LCD（約 210 萬點）" },
      { label: "觀景窗", value: "光學五稜鏡，視野率約 100%" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "儲存媒介", value: "雙 SD 卡槽（UHS-II 支援）" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 146 × 124 × 78.5 mm" },
      { label: "重量", value: "約 1005 g（含電池與卡）" },
      { label: "電池", value: "EN-EL15a" },
      { label: "產地", value: "泰國" },
    ],

    "Nikon MB-D18 電池手把": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "MB-D18" },
      { label: "適用機種", value: "Nikon D850" },
      { label: "電池支援", value: "1 顆 EN-EL18a / 6 顆 AA 電池" },
      { label: "增加續航", value: "延長拍攝時間，提升握持穩定性" },
      { label: "操控按鍵", value: "垂直快門鈕、主轉盤、副轉盤、AE-L / AF-L 按鈕" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 156 × 83 × 60 mm" },
      { label: "重量", value: "約 340 g（不含電池）" },
      { label: "附屬配件", value: "電池蓋" },
    ],

    "Nikon SB-5000 閃光燈": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "SB-5000" },
      { label: "閃光指數", value: "GN34（ISO 100，35mm）" },
      { label: "閃燈覆蓋範圍", value: "24–120mm（自動變焦）" },
      { label: "閃光模式", value: "i-TTL / 手動 / 多重閃光" },
      { label: "無線控制", value: "支援無線閃光系統" },
      { label: "冷卻系統", value: "內建散熱風扇" },
      { label: "電池", value: "4 顆 AA 電池" },
      { label: "尺寸", value: "約 74 × 133 × 104 mm" },
      { label: "重量", value: "約 420 g（不含電池）" },
    ],

    "Nikon Z 50mm f/1.8 S": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "Z 50mm f/1.8 S" },
      { label: "焦段", value: "50mm" },
      { label: "最大光圈", value: "f/1.8" },
      { label: "最小光圈", value: "f/16" },
      { label: "鏡頭結構", value: "10 組 15 枚" },
      { label: "光圈葉片", value: "7 片圓形光圈" },
      { label: "最近對焦距離", value: "0.4 公尺" },
      { label: "最大放大倍率", value: "0.16 倍" },
      { label: "對焦驅動", value: "超音波馬達（STM）" },
      { label: "濾鏡尺寸", value: "58mm" },
      { label: "尺寸", value: "約 75 × 75 mm" },
      { label: "重量", value: "約 415 g" },
      { label: "防塵防滴", value: "具備" },
      { label: "接環類型", value: "Nikon Z" },
      { label: "產地", value: "泰國" },
    ],

    "Nikon Z30": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "Z30" },
      { label: "感光元件", value: "APS-C CMOS" },
      { label: "有效畫素", value: "約 2088 萬像素" },
      { label: "影像處理器", value: "EXPEED 6" },
      { label: "感光度範圍", value: "ISO 100–51200" },
      { label: "對焦系統", value: "混合式對焦系統（273 點）" },
      { label: "快門速度", value: "1/4000 至 30 秒" },
      { label: "連拍速度", value: "約 11 fps" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "螢幕", value: "3 吋可翻轉觸控 LCD" },
      { label: "重量", value: "約 395 g（含電池與記憶卡）" },
      { label: "尺寸", value: "約 128 × 93 × 77 mm" },
      { label: "防塵防滴", value: "無" },
      { label: "產地", value: "泰國" },
    ],

    "Nikon Z6": [
      { label: "品牌", value: "Nikon" },
      { label: "型號", value: "Z6" },
      { label: "感光元件", value: "全片幅 CMOS" },
      { label: "有效畫素", value: "約 2450 萬像素" },
      { label: "影像處理器", value: "EXPEED 6" },
      { label: "感光度範圍", value: "ISO 100–51200（可擴展）" },
      { label: "對焦系統", value: "273 點混合式對焦" },
      { label: "防手震系統", value: "機身五軸防震" },
      { label: "快門速度", value: "1/8000 至 30 秒" },
      { label: "連拍速度", value: "約 12 fps" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "螢幕", value: "3.2 吋可翻轉觸控 LCD" },
      { label: "電子觀景窗", value: "369 萬點 OLED" },
      { label: "儲存媒介", value: "雙卡槽（XQD / CFexpress + SD）" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 134 × 100.5 × 67.5 mm" },
      { label: "重量", value: "約 675 g（含電池與卡）" },
      { label: "產地", value: "泰國" },
    ],

    "Olympus Tough TG-6": [
      { label: "品牌", value: "Olympus" },
      { label: "型號", value: "Tough TG-6" },
      { label: "感光元件", value: "1/2.3 吋 1200 萬畫素 BSI CMOS" },
      { label: "影像處理器", value: "TruePic VIII" },
      { label: "鏡頭規格", value: "25–100mm 等效（f/2.0–4.9），4 倍光學變焦" },
      { label: "防水性能", value: "可下潛至 15 米" },
      { label: "防摔性能", value: "可承受 2.1 米墜落" },
      { label: "抗壓性能", value: "可承受 100kgf 壓力" },
      { label: "抗凍性能", value: "可耐 -10°C 環境" },
      { label: "防塵性能", value: "IP6X 等級" },
      { label: "錄影功能", value: "4K/30p、Full HD 120fps" },
      { label: "特殊拍攝模式", value: "水下 HDR、顯微攝影、水下顯微" },
      { label: "螢幕", value: "3 吋 TFT LCD（104 萬點）" },
      { label: "感測功能", value: "GPS、電子羅盤、氣壓計、溫度感測" },
      { label: "支援 RAW", value: "支援 RAW 格式拍攝" },
      { label: "記憶卡", value: "SD / SDHC / SDXC（支援 UHS-I）" },
      { label: "電池", value: "LI-92B 可充電鋰電池" },
      { label: "尺寸", value: "約 113 × 66 × 32.4 mm" },
      { label: "重量", value: "約 253g（含電池與記憶卡）" },
    ],
    "Olympus OM-D E-M1 Mark III": [
      { label: "品牌", value: "Olympus" },
      { label: "型號", value: "OM-D E-M1 Mark III" },
      { label: "感光元件", value: "2037 萬畫素 4/3 吋 Live MOS" },
      { label: "影像處理器", value: "TruePic IX" },
      { label: "防手震系統", value: "五軸防震，最高 7.5 級補償（搭配 Sync IS 鏡頭）" },
      { label: "自動對焦系統", value: "121 點十字型相位 + 對比 AF，支援人臉與眼部偵測" },
      { label: "ISO 感光度", value: "ISO 200–25600（可擴展至 ISO 64）" },
      { label: "快門速度", value: "1/8000 秒（機械）、1/32000 秒（電子）" },
      { label: "高速連拍", value: "60 fps（電子）、15 fps（機械）" },
      { label: "螢幕", value: "3 吋可翻轉觸控 LCD（104 萬點）" },
      { label: "觀景窗", value: "236 萬點 OLED 電子觀景窗" },
      { label: "錄影功能", value: "Cinema 4K / UHD 4K、OM-Log400" },
      { label: "特殊功能", value: "手持高解析、即時 ND、星空對焦、Pro Capture" },
      { label: "記憶卡插槽", value: "雙 SD 卡槽（Slot 1 支援 UHS-II）" },
      { label: "電池", value: "BLH-1，支援 USB-C PD 快速充電" },
      { label: "機身材質", value: "鎂合金，防塵防滴抗凍" },
      { label: "尺寸", value: "約 134.1 × 90.9 × 68.9 mm" },
      { label: "重量", value: "約 504g（含電池與記憶卡）" },
    ],
    "Olympus HLD-9 電池手把": [
      { label: "品牌", value: "Olympus" },
      { label: "型號", value: "HLD-9" },
      { label: "適用機種", value: "OM-D E-M1 Mark II / Mark III" },
      { label: "電池支援", value: "可容納 1 顆 BLH-1 鋰電池" },
      { label: "續航延長", value: "搭配相機本體可延長拍攝時間" },
      { label: "防塵防滴", value: "具備，與機身相同等級" },
      { label: "尺寸", value: "約 121.3 × 49.3 × 73.8 mm" },
      { label: "重量", value: "約 230 g（不含電池）" },
      { label: "附屬配件", value: "握把電池匣" },
    ],
    "Olympus M.Zuiko 12-40mm f/2.8 PRO": [
      { label: "品牌", value: "Olympus" },
      { label: "型號", value: "M.Zuiko Digital ED 12-40mm f/2.8 PRO" },
      { label: "鏡頭格式", value: "Micro Four Thirds" },
      { label: "焦段", value: "12–40mm（等效 24–80mm）" },
      { label: "最大光圈", value: "f/2.8（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "9 組 14 枚（含非球面與 ED 鏡片）" },
      { label: "對焦系統", value: "MSC 馬達，快速安靜對焦" },
      { label: "最近對焦距離", value: "0.2 公尺（全焦段）" },
      { label: "最大放大倍率", value: "0.3x（等效 0.6x）" },
      { label: "濾鏡尺寸", value: "62mm" },
      { label: "防塵防滴", value: "具備，抗凍設計" },
      { label: "尺寸", value: "約 69.9 × 84 mm" },
      { label: "重量", value: "約 382g" },
      { label: "附屬配件", value: "原廠遮光罩、鏡頭前後蓋、鏡頭袋（依實際提供）" },
    ],

    "Panasonic DMW-XLR1 麥克風轉接器": [
      { label: "品牌", value: "Panasonic" },
      { label: "型號", value: "DMW-XLR1" },
      { label: "類型", value: "麥克風轉接器" },
      { label: "輸入介面", value: "2 x XLR/TRS 輸入" },
      { label: "音訊輸出", value: "3.5mm 立體聲迷你插孔" },
      { label: "電源供應", value: "相機電源" },
      { label: "附屬配件", value: "防風罩、連接線" },
      { label: "尺寸", value: "約 140 × 58 × 35 mm" },
      { label: "重量", value: "約 130 g" },
    ],
    "Panasonic Lumix LX100 II": [
      { label: "品牌", value: "Panasonic" },
      { label: "型號", value: "Lumix LX100 II" },
      { label: "感光元件", value: "Micro Four Thirds CMOS" },
      { label: "有效畫素", value: "約 1700 萬像素" },
      { label: "鏡頭焦段", value: "24–75mm（等效全片幅）" },
      { label: "最大光圈", value: "f/1.7–2.8" },
      { label: "影像處理器", value: "Venus Engine" },
      { label: "感光度範圍", value: "ISO 200–25600" },
      { label: "錄影功能", value: "4K UHD 30p" },
      { label: "螢幕", value: "3 吋可翻轉觸控 LCD" },
      { label: "尺寸", value: "約 115 × 66 × 64 mm" },
      { label: "重量", value: "約 392 g（含電池與記憶卡）" },
    ],
    "Panasonic Lumix S Pro 70-200mm f/4": [
      { label: "品牌", value: "Panasonic" },
      { label: "型號", value: "Lumix S Pro 70-200mm f/4" },
      { label: "焦段", value: "70–200mm" },
      { label: "最大光圈", value: "f/4（恆定）" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "15 組 20 枚（含非球面與 ED 鏡片）" },
      { label: "光圈葉片", value: "9 片圓形光圈" },
      { label: "最近對焦距離", value: "約 0.6 公尺" },
      { label: "最大放大倍率", value: "0.28 倍" },
      { label: "對焦驅動", value: "線性馬達" },
      { label: "濾鏡尺寸", value: "77mm" },
      { label: "尺寸", value: "約 89 × 176 mm" },
      { label: "重量", value: "約 1035 g" },
      { label: "防塵防滴", value: "具備" },
      { label: "接環類型", value: "L-Mount" },
    ],
    "Panasonic S5": [
      { label: "品牌", value: "Panasonic" },
      { label: "型號", value: "Lumix S5" },
      { label: "感光元件", value: "全片幅 CMOS" },
      { label: "有效畫素", value: "約 2420 萬像素" },
      { label: "影像處理器", value: "Venus Engine" },
      { label: "感光度範圍", value: "ISO 100–51200（可擴展至 50–204800）" },
      { label: "對焦系統", value: "對比式及相位混合對焦" },
      { label: "防手震系統", value: "5 軸機身防震" },
      { label: "快門速度", value: "1/8000 至 60 秒，支援 B 快門" },
      { label: "連拍速度", value: "約 7 fps" },
      { label: "錄影功能", value: "4K UHD 60p / 10-bit 4:2:2 內錄" },
      { label: "螢幕", value: "3 吋可翻轉觸控 LCD" },
      { label: "電子觀景窗", value: "約 368 萬點 OLED" },
      { label: "儲存媒介", value: "雙 SD 卡槽（支援 UHS-II）" },
      { label: "防塵防滴", value: "具備" },
      { label: "尺寸", value: "約 132.6 × 97.1 × 81.9 mm" },
      { label: "重量", value: "約 714 g（含電池與卡）" },
    ],

    "Pentax D-BG7 電池手把": [
      { label: "品牌", value: "Pentax" },
      { label: "型號", value: "D-BG7" },
      { label: "適用機種", value: "Pentax KP" },
      { label: "電池類型", value: "1 顆 D-LI109 鋰電池（需另購）" },
      { label: "防塵防滴", value: "具備，與 Pentax KP 相同等級" },
      { label: "材質", value: "高強度塑料" },
      { label: "尺寸", value: "約 131 × 36 × 65 mm" },
      { label: "重量", value: "約 180 g（不含電池）" },
      { label: "顏色", value: "黑色" },
      { label: "產地", value: "日本" },
    ],
    "Pentax FA 31mm f/1.8 Limited": [
      { label: "品牌", value: "Pentax" },
      { label: "型號", value: "FA 31mm f/1.8 Limited" },
      { label: "焦段", value: "31mm（APS-C 等效約 47mm）" },
      { label: "最大光圈", value: "f/1.8" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡片結構", value: "7 群 9 枚（含特殊低色散與非球面鏡片）" },
      { label: "光圈葉片數", value: "9 枚圓形光圈" },
      { label: "最近對焦距離", value: "約 0.3 公尺" },
      { label: "放大倍率", value: "約 0.16×" },
      { label: "對焦方式", value: "傳統機身馬達驅動，支援 Quick-Shift Focus" },
      { label: "濾鏡尺寸", value: "58mm" },
      { label: "尺寸", value: "約 65 × 69 mm" },
      { label: "重量", value: "約 345 g" },
      { label: "鏡身材質", value: "全金屬，陽極處理" },
      { label: "適用接環", value: "Pentax K 接環" },
      { label: "產地", value: "日本" },
    ],
    "Pentax K-1 Mark II": [
      { label: "品牌", value: "Pentax" },
      { label: "型號", value: "K-1 Mark II" },
      { label: "感光元件", value: "35mm 全片幅 CMOS（無低通濾鏡）" },
      { label: "有效畫素", value: "約 3640 萬像素" },
      { label: "影像處理器", value: "PRIME IV 與加速單元" },
      { label: "感光度範圍", value: "ISO 100–819200" },
      { label: "對焦系統", value: "SAFOX 12，33 點自動對焦（25 點十字型）" },
      { label: "防手震系統", value: "內建五軸 SR II，最高 5 級補償" },
      { label: "特殊功能", value: "Pixel Shift Resolution II，手持像素移位模式" },
      { label: "螢幕", value: "3.2 吋可翻轉 TFT LCD（約 103.7 萬點）" },
      { label: "觀景窗", value: "光學五稜鏡，視野率約 100%，放大倍率 0.7 倍" },
      { label: "快門速度", value: "1/8000 至 30 秒，支援 B 快門" },
      { label: "連拍速度", value: "約 4.4 fps" },
      { label: "影片錄製", value: "Full HD 1080p" },
      { label: "儲存媒介", value: "雙 SD 卡槽，支援 UHS-I" },
      { label: "防塵防滴", value: "鎂合金機身，87 處密封" },
      { label: "GPS/電子羅盤", value: "內建，支援 ASTROTRACER" },
      { label: "尺寸", value: "約 136.5 × 110 × 85.5 mm" },
      { label: "重量", value: "約 1010 g（含電池與卡）" },
      { label: "電池", value: "D-LI90 鋰電池" },
      { label: "其他特色", value: "Wi-Fi、USB 3.0、HDMI 輸出" },
      { label: "產地", value: "日本" },
    ],
    "Pentax Q-S1": [
      { label: "品牌", value: "Pentax" },
      { label: "型號", value: "Q-S1" },
      { label: "感光元件", value: "1/1.7 吋 背照式 CMOS" },
      { label: "有效畫素", value: "約 1240 萬畫素" },
      { label: "影像處理器", value: "Q ENGINE" },
      { label: "感光度範圍", value: "ISO 100–12800" },
      { label: "防手震系統", value: "感光元件位移防震（SR）" },
      { label: "對焦系統", value: "對比式自動對焦（臉部偵測、追蹤對焦）" },
      { label: "快門速度", value: "1/2000–30 秒，支援 B 快門" },
      { label: "連拍速度", value: "約 5 fps" },
      { label: "螢幕", value: "3 吋 TFT LCD，約 46 萬點" },
      { label: "錄影功能", value: "Full HD 1080p / 30fps" },
      { label: "拍攝模式", value: "P、Tv、Av、M、SCN、藝術濾鏡" },
      { label: "支援 RAW 格式", value: "有（DNG）" },
      { label: "儲存媒介", value: "SD / SDHC / SDXC" },
      { label: "鏡頭接環", value: "Pentax Q" },
      { label: "電池類型", value: "D-LI68 鋰電池" },
      { label: "尺寸", value: "約 105 × 58 × 34 mm" },
      { label: "重量", value: "約 203 g（不含鏡頭）" },
      { label: "顏色選項", value: "多色（黑、銀、金、紅、白）" },
    ],

    "Sony A1": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "Alpha 1" },
      { label: "感光元件", value: "5010 萬畫素 全片幅 Exmor RS CMOS" },
      { label: "影像處理器", value: "雙 BIONZ XR" },
      { label: "ISO 感光度", value: "100–32,000（可擴展至 50–102,400）" },
      { label: "連拍速度", value: "最高 30 fps（電子快門）" },
      { label: "對焦系統", value: "759 點相位檢測，自動眼部追蹤（人/動物/鳥）" },
      { label: "錄影功能", value: "8K 30p / 4K 120p / 10-bit 4:2:2" },
      { label: "螢幕", value: "3 吋可翻式觸控螢幕（144 萬點）" },
      { label: "電子觀景窗", value: "944 萬點 OLED，放大率 0.9x" },
      { label: "卡槽", value: "雙卡槽（CFexpress Type A + SD UHS-II）" },
      { label: "無線連接", value: "Wi-Fi、Bluetooth、1000BASE-T LAN" },
      { label: "電池", value: "NP-FZ100，支援 USB PD 快充" },
      { label: "尺寸", value: "約 128.9 × 96.9 × 80.8 mm" },
      { label: "重量", value: "約 737g（含電池與記憶卡）" },
    ],
    "Sony A7 III": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "A7 III" },
      { label: "感光元件", value: "2420 萬畫素 全片幅 Exmor R CMOS" },
      { label: "影像處理器", value: "BIONZ X" },
      { label: "ISO 感光度", value: "100–51,200（可擴展至 50–204,800）" },
      { label: "連拍速度", value: "最高 10 fps（機械 / 電子快門）" },
      { label: "對焦系統", value: "693 點相位 + 425 點對比，眼部追蹤對焦" },
      { label: "錄影功能", value: "4K 30p、6K 超取樣、S-Log2/3、HLG" },
      { label: "螢幕", value: "3 吋翻轉觸控螢幕（92 萬點）" },
      { label: "電子觀景窗", value: "236 萬點 OLED" },
      { label: "卡槽", value: "雙卡槽（SD UHS-II）" },
      { label: "無線連接", value: "Wi-Fi、NFC、Bluetooth" },
      { label: "電池", value: "NP-FZ100" },
      { label: "尺寸", value: "126.9 × 95.6 × 73.7 mm" },
      { label: "重量", value: "約 650g（含電池）" },
    ],
    "Sony FE 16-35mm f/2.8 GM": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "FE 16-35mm f/2.8 GM" },
      { label: "焦段", value: "16–35mm" },
      { label: "最大光圈", value: "f/2.8" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "13 組 16 枚（含 2 XA、3 ED 鏡片）" },
      { label: "最近對焦距離", value: "約 28cm" },
      { label: "最大放大倍率", value: "0.19 倍" },
      { label: "對焦系統", value: "雙線性馬達" },
      { label: "濾鏡尺寸", value: "82mm" },
      { label: "光圈葉片", value: "11 枚圓形光圈" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 88.5 × 121.6 mm" },
      { label: "重量", value: "約 680g" },
      { label: "接環", value: "Sony E-mount（全片幅）" },
    ],
    "Sony FE 24-70mm F2.8 GM": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "FE 24-70mm f/2.8 GM" },
      { label: "焦段", value: "24–70mm" },
      { label: "最大光圈", value: "f/2.8" },
      { label: "最小光圈", value: "f/22" },
      { label: "鏡頭結構", value: "13 組 18 枚（含 1 XA、2 ED、1 Super ED）" },
      { label: "最近對焦距離", value: "約 38cm" },
      { label: "最大放大倍率", value: "0.24 倍" },
      { label: "對焦系統", value: "DDSSM 超音波馬達" },
      { label: "濾鏡尺寸", value: "82mm" },
      { label: "光圈葉片", value: "9 枚圓形" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 87.6 × 136 mm" },
      { label: "重量", value: "約 886g" },
      { label: "接環", value: "Sony E-mount（全片幅）" },
    ],
    "Sony FE 85mm f/1.4 GM": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "FE 85mm f/1.4 GM" },
      { label: "焦段", value: "85mm" },
      { label: "最大光圈", value: "f/1.4" },
      { label: "最小光圈", value: "f/16" },
      { label: "鏡頭結構", value: "8 組 11 枚（含 1 XA、3 ED）" },
      { label: "最近對焦距離", value: "85 cm" },
      { label: "最大放大倍率", value: "0.12 倍" },
      { label: "對焦系統", value: "環型超音波馬達（SSM）" },
      { label: "光圈葉片", value: "11 枚圓形" },
      { label: "濾鏡尺寸", value: "77mm" },
      { label: "光圈環", value: "有，支援無段切換" },
      { label: "防塵防滴", value: "有" },
      { label: "尺寸", value: "約 89.5 × 107.5 mm" },
      { label: "重量", value: "約 820g" },
      { label: "接環", value: "Sony E-mount（全片幅）" },
    ],
    "Sony RX100 VII": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "RX100 VII" },
      { label: "感光元件", value: "1 吋 Exmor RS CMOS（約 2010 萬像素）" },
      { label: "影像處理器", value: "BIONZ X + 前端 LSI" },
      { label: "鏡頭", value: "ZEISS 24–200mm f/2.8–4.5" },
      { label: "對焦系統", value: "357 點相位 + 425 點對比，眼部追焦（人/動物）" },
      { label: "連拍速度", value: "最高 20fps 無黑屏連拍" },
      { label: "錄影功能", value: "4K UHD 30p、S-Log3、HLG、外接麥克風支援" },
      { label: "螢幕", value: "3 吋可翻式觸控 LCD（約 92 萬點）" },
      { label: "觀景窗", value: "0.39 吋 236 萬點 OLED EVF" },
      { label: "音訊介面", value: "3.5mm 麥克風輸入" },
      { label: "無線連接", value: "Wi-Fi、藍牙" },
      { label: "電池", value: "NP-BX1（USB 充電）" },
      { label: "尺寸", value: "約 102 × 58 × 43 mm" },
      { label: "重量", value: "約 302g（含電池）" },
    ],
    "Sony ZV-1": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "ZV-1" },
      { label: "感光元件", value: "1 吋 Exmor RS CMOS（約 2010 萬像素）" },
      { label: "影像處理器", value: "BIONZ X" },
      { label: "鏡頭", value: "ZEISS 24–70mm f/1.8–2.8" },
      { label: "對焦系統", value: "315 點相位 + 對比偵測，眼部追焦、產品展示模式" },
      { label: "影像穩定", value: "光學 + 電子穩定（影片）" },
      { label: "錄影功能", value: "4K UHD 30p、FHD 120p、S-Log3、HLG" },
      { label: "螢幕", value: "3 吋側翻式觸控 LCD（92 萬點）" },
      { label: "音訊", value: "三膠囊麥克風 + 防風罩 + 3.5mm 麥克風輸入" },
      { label: "無線連接", value: "Wi-Fi、藍牙" },
      { label: "電池", value: "NP-BX1（USB 充電）" },
      { label: "尺寸", value: "約 105.5 × 60.0 × 43.5 mm" },
      { label: "重量", value: "約 294g（含電池）" },
    ],
    "Sony VG-C4EM 電池手把": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "VG-C4EM" },
      { label: "適用機種", value: "α1、α7R IV/V、α7 IV、α7S III 等" },
      { label: "電池支援", value: "2 顆 NP-FZ100（需另購）" },
      { label: "操控介面", value: "快門鈕、搖桿、前後轉盤、自訂鍵" },
      { label: "材質", value: "鎂合金" },
      { label: "防塵防滴", value: "有（與相機相同等級）" },
      { label: "電源供應", value: "由相機供電" },
      { label: "尺寸", value: "約 135.1 × 106.6 × 63.9 mm" },
      { label: "重量", value: "約 290g（不含電池）" },
    ],
    "Sony XLR-K3M 專業麥克風轉接器": [
      { label: "品牌", value: "Sony" },
      { label: "型號", value: "XLR-K3M" },
      { label: "輸入介面", value: "2 x XLR/TRS，1 x 3.5mm 麥克風輸入" },
      { label: "音訊處理", value: "數位傳輸（透過 MI 熱靴）" },
      { label: "幻象電源", value: "+48V 支援" },
      { label: "音量控制", value: "每通道獨立旋鈕" },
      { label: "增益切換", value: "+20dB / 0dB / -20dB" },
      { label: "低切濾波", value: "150Hz / 100Hz / OFF" },
      { label: "供電方式", value: "相機 MI 熱靴供電" },
      { label: "附屬麥克風", value: "ECM-XM1 指向性麥克風 + 防風罩" },
      { label: "尺寸", value: "約 96 × 92.5 × 47 mm" },
      { label: "重量", value: "約 187g（含麥克風）" },
      { label: "相容機種", value: "Sony α1、α7 IV、FX3、ZV-E1 等支援數位音訊的機種" },
    ],
  };

  const matchedBrand = Object.keys(specificationSets).find(
    brand => name?.toLowerCase() === brand.toLowerCase()
  );

  const selectedSpecs = specificationSets[matchedBrand] || [];

  return (
    <div className="bg-white rounded-1 px-6 py-8 row">
      <table className="table table-bordered align-middle">
        <tbody>
          {selectedSpecs.map((spec, index) => (
            <tr key={index}>
              <th className="text-nowrap bg-light text-secondary" style={{ width: "20%" }}>
                {spec.label}
              </th>
              <td>{spec.value}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ProductSpecificationsPanel;
